version: '3.5'

services:
  api:
    build: .
    image: labbsr0x/score-api:latest
    environment:
      - SCORE_ENVIRONMENT=DEV
      - DB_MONGO_URI=mongodb://root:root@mongo:27017/githunter?authSource=admin
      - GITHUNTER_API_URL=http://githunter-api.labbs.com.br
      - GITHUNTER_USER_ENDPOINT=/user
      - GITHUNTER_USER_SIMPLE_ENDPOINT=/user-simple
      - APP_LOG_LEVEL=INFO
      - APP_PORT=3000
    ports:
      - 3000:3000
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    restart: always
    links:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    restart: always